version : '3'

services:
    players:
        build: './players'
        ports:
            - 3000:80
        volumes:
            - ./players:/app
            
    site:
        build: './site'
        ports: 
            - 4000:80
        depends_on: 
            - players
        volumes:
            - ./site:/app
        
