version: '3'

services: 
    db:
        build: './db'
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
    apparel:
        build: './apparel'
        volumes:
            - ./apparel:/app
        ports:
            - 5001:80
        depends_on: 
            - db
    prices:
        build: './prices'
        volumes:
            - ./prices:/app
        ports:
            - 6000:80
        depends_on:
            - apparel
            