version: '3'

services: 
    db:
        build: './db'
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        networks:
            - core
    apparel:
        build: './apparel'
        volumes:
            - ./apparel:/app
        ports:
            - 5001:80
        depends_on: 
            - db
        networks:
            - core
    prices:
        build: './prices'
        volumes:
            - ./prices:/app
        ports:
            - 6000:80
        depends_on:
            - apparel
        networks:
            - core
            - site
    site:
        build: './site'
        volumes: 
            - ./site:/app
        ports:
            - 7000:80
        depends_on:
            - prices
        networks:
            - site
networks:
  core:
    driver: bridge
  site:
    driver: bridge
            