version: '3'

services: 
    db:
        build: './db'
        environment:
            POSTGRES_PASSWORD: password
    apparel:
        build: './apparel'
        volumes:
            - ./apparel:/app
        ports:
            - 4000:80
        depends_on: 
            - db
            